---
title: "R Notebook"
output: html_notebook
---


Setup
```{r message = F, warning = F}
if (!require("glmnet")) {
  install.packages("glmnet")
  library(glmnet)
}
if (!require("rsample")) {
  install.packages("rsample")
  library(rsample)
}
```

load data
```{r message = F, warning = F}
ldim <- read.csv("../data/lowDim_dataset.csv")
hdim <- read.csv("../data/highDim_dataset.csv")

# Low Dimension
lA <- ldim$A
lY <- ldim$Y
lData <- ldim[,-c(1,2)]

# High Dimension
hA <- hdim$A
hY <- hdim$Y
hData <- hdim[, -c(1,2)]
```

Prop_score
```{r message = F, warning = F}
if (!require("rpart")) install.packages("rpart")
source("../lib/propensity_score.R")
#Calculate the propensity score of each observation in low and high dimensional data
ps_low <- propensity_score_ld(ldim)
ps_high <- propensity_score_hd(hdim)
```

Low Dim
```{r message = F, warning = F}
#Set the starting time
start <- Sys.time()

#build the model
lr_low1 <- glm(formula=Y~ .,data = ldim[which(ldim$A=='1'),])
lr_low0 <- glm(formula=Y~ .,data = ldim[which(ldim$A=='0'),])

#make predictions
lm1 <- predict(lr_low1,ldim[,-c(1)])
lm0 <- predict(lr_low0,ldim[,-c(1)])

#compute the ATE using the formula
ATE_low <- sum((lA*lY-(lA-ps_low)*lm1)/ps_low)/dim(ldim)[1] -sum(((1-lA)*lY+(lA-ps_low)*lm0)/(1-ps_low))/dim(ldim)[1]
ATE_low

#stop the timer
end <- Sys.time()

#print the time
paste("Low Dim Running time :",difftime(end,start))
```

High Dim
```{r message = F, warning = F}
#Set the starting time
start <- Sys.time()

#build the model
lr_high1 <- glm(formula=Y~ .,data = hdim[which(hdim$A=='1'),])
lr_high0 <- glm(formula=Y~ .,data = hdim[which(hdim$A=='0'),])

#make predictions
hm1 <- predict(lr_high1,hdim[,-c(1)])
hm0 <- predict(lr_high0,hdim[,-c(1)])

#compute the ATE using the formula
ATE_high <- sum((hA*hY-(hA-ps_high)*hm1)/ps_high)/dim(hdim)[1] -sum(((1-hA)*hY+(hA-ps_high)*hm0)/(1-ps_high))/dim(hdim)[1]
ATE_high

#print the time
paste("High Dim Running time :",difftime(Sys.time(),start))
```



